[package]
name = "b64"
version = "0.1.0"
authors = ["Nick Hackman <nicholazwow@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmarks"
harness = false
